### ISSUE TITLE
Clarifying Step 2

### ISSUE THREAD

**Issue by peterpme** [ncuillery/rn-diff#3]
Hey,

Great job putting this together! This is awesome!

I was hoping you could clear up some issues with Step 2 for me.
- Where is exactly do "s-ios" and "s-java" live?
- Am I supposed to clone & checkout the version I want, then replace all instances of RnDiffApp with my app? Then replace all instances of RnDiffApp in the patch file as well?
- When I try running the sed command, I get `no such file or directory`

Thanks again!

**Comment by ncuillery** [comment]
Hi Peter,

You are not supposed to clone or checkout this repository 😊 

You only have to download the correct patch for your current & next versions, this one for example:
https://github.com/ncuillery/rn-diff/compare/rn-0.33.0...rn-0.34.0.diff

The problem is: this patch is not suitable for your app, it has been generated from the demo app RnDiffApp, so you have to modify it, that's the point of the `sed` command.

`sed` is the most twisted unix command I ever know: 
- `s` is the replace command (dont ask me why)
- `-` is the separator, it could be an other character (it's usually `/` but I couldn't use it here because the `/` in the string I want to replace.

`s-ios/RnDiffApp-ios/MyApp-` simply replaces all occurrences of `ios/RnDiffApp` by `ios/MyApp`, there is nothing you can't do manually with a text editor.

FYI, I know this process is hacky, I'm working on integrating rn-diff in the core of React Native for  a better developer experience. Stay tuned !

**Comment by peterpme** [comment]
Thanks again for the help! You are awesome!
