### ISSUE TITLE
RN 0.34 AppManifest.xml is missing `android:name` attribute in `application` tag

### ISSUE THREAD

**Issue by rigdern** [ncuillery/rn-diff#8]
- [FB's template](https://github.com/facebook/react-native/blob/v0.34.0/local-cli/generator-android/templates/src/app/src/main/AndroidManifest.xml#L14) for `AndroidManifest.xml` for RN 0.34 has an `android:name` attribute.
- [In rn-diff's app](https://github.com/ncuillery/rn-diff/blob/rn-0.34.0/RnDiffApp/android/app/src/main/AndroidManifest.xml#L6-L10) for RN 0.34, `AndroidManifest.xml` is missing the `android:name` attribute in its `application` tag.

**Comment by ncuillery** [comment]
You're right, there was an issue with the former Yeoman generator used by the `react-native upgrade` command: only files located in `android` and `android/app` directories were upgraded. 
See [this block](https://github.com/facebook/react-native/blob/eddc2c90f693739273583b74fc70148182b9f143/local-cli/generator-android/index.js#L61-L70).

The `AndroidManifest.xml` is located in a sub-directory `android/app/src/main` that wasn't selected by the glob pattern. 

It means that the `AndroidManifest.xml` of the RnDiffApp hasn't been upgraded since the init of the app (with RN 0.23.0). That explains the difference.

Two other files are concerned as well:
- android/keystores/BUCK
- android/keystores/debug.keystore.properties

Fortunately, the RN team replaced the Yeoman generator by a home-made solution in RN 0.39.0 which upgrades these files correctly. 

Note that the [compare view from 0.38.0 to 0.39.0](https://github.com/ncuillery/rn-diff/compare/rn-0.38.0...rn-0.39.0#diff-ce925d749acbf5fb99afc2d465a0f352) is not relevant for the `AndroidManifest.xml` file. Actually, it shows the diff from 0.23.0 to 0.39.0 (because the RnDiffApp has been generated in 0.23.0).

**Comment by ncuillery** [comment]
I close this because there's nothing I can do. I have referenced the issue in the [README.md#known-issues](https://github.com/ncuillery/rn-diff/blob/master/README.md#known-issues)
